seed: 42
csv_path: data/processed/combined.csv
metrics_path: reports/metrics.json
profile: false
profile_path: reports/profile.pstats

id_col: "ScanDir ID"
feature_cols:
  - Age
  - Gender
  - Handedness
  - Verbal IQ
  - Performance IQ
  - Full4 IQ
  - ADHD Index
  - Inattentive
  - Hyper/Impulsive

n_clusters: 5

use_wandb: true
wandb_project: mlops_group35
wandb_mode: online
wandb_run_name: null
